services:
  express:
    build: .
    container_name: express
    ports:
      - "3000:3000"
    depends_on:
      - redis

  redis:
    image: "redis"
    container_name: redis
    ports: 
      - "6379:6379"