services:
  back-end:
    image: node
    container_name: test-backend
    restart: always
    volumes:
      - ./back:/express/
    working_dir: /express/
    command: ["sh", "-c", "npm install && node app.js"]
    ports:
      - "8080:8080"
    networks:
      - frontend_network
      - backend_network

  front-end:
    image: node
    container_name: test-frontend
    restart: always
    volumes:
      - ./front/chmur_front:/app/
    working_dir: /app/
    command: ["sh", "-c", "npm install && npm run dev"]
    ports:
      - "3000:3000"
    networks:
      - frontend_network

  mongo-db:
    image: mongo
    container_name: test-db
    restart: always
    environment:
      MONGO_INITDB_DATABASE: mydb
    networks:
      - backend_network

networks:
  frontend_network:
    driver: bridge

  backend_network:
    driver: bridge